name: "Lint and Format Code"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [python, javascript]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      if: matrix.language == 'python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Flake8 and Black
      if: matrix.language == 'python'
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Run Flake8
      if: matrix.language == 'python'
      run: |
        flake8 .

    - name: Run Black
      if: matrix.language == 'python'
      run: |
        black --check .

    - name: Set up Node.js
      if: matrix.language == 'javascript'
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      if: matrix.language == 'javascript'
      run: |
        npm install

    - name: Run ESLint
      if: matrix.language == 'javascript'
      run: |
        npx eslint .
